-- Migration: Add new columns for JSON schema v2
-- Created: 2026-02-16

-- Añadir nuevas columnas a la tabla skills
ALTER TABLE skills 
  ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS difficulty TEXT DEFAULT 'medium',
  ADD COLUMN IF NOT EXISTS uselessness_score INTEGER DEFAULT 5,
  ADD COLUMN IF NOT EXISTS votes_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS warnings TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS original_prompt TEXT DEFAULT '';

-- Renombrar/migrar columna prompt (ahora es original_prompt)
-- Nota: Si había datos en prompt, deberíamos migrarlos
-- UPDATE skills SET original_prompt = prompt WHERE prompt IS NOT NULL;

-- Eliminar columna antigua prompt (opcional, después de verificar migración)
-- ALTER TABLE skills DROP COLUMN IF EXISTS prompt;

-- Crear índices para búsquedas frecuentes
CREATE INDEX IF NOT EXISTS idx_skills_tags ON skills USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_skills_difficulty ON skills (difficulty);
CREATE INDEX IF NOT EXISTS idx_skills_votes_count ON skills (votes_count DESC);
CREATE INDEX IF NOT EXISTS idx_skills_uselessness_score ON skills (uselessness_score DESC);

-- Tabla para votos anónimos (viralidad sin fricción)
CREATE TABLE IF NOT EXISTS votes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  skill_id TEXT REFERENCES skills(id) ON DELETE CASCADE,
  ip_hash TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índice único: 1 voto por IP por skill
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_vote_per_ip ON votes(skill_id, ip_hash);

-- Índice para conteo rápido
CREATE INDEX IF NOT EXISTS idx_votes_skill_id ON votes (skill_id);

-- Eliminar columna antigua prompt (ya migrada a original_prompt)
ALTER TABLE skills DROP COLUMN IF EXISTS prompt;

-- Comentarios para documentación
COMMENT ON TABLE skills IS 'Fake skills generated by users';
COMMENT ON COLUMN skills.tags IS 'Array de tags predefinidos para filtrado';
COMMENT ON COLUMN skills.difficulty IS 'Nivel de dificultad: trivial, easy, medium, hard, impossible';
COMMENT ON COLUMN skills.uselessness_score IS 'Puntuación 1-10 de inutilidad (10 = completamente absurdo)';
COMMENT ON COLUMN skills.votes_count IS 'Contador de votos anónimos (para Hall of Shame)';
COMMENT ON COLUMN skills.warnings IS 'Array de advertencias humorísticas obligatorias';
COMMENT ON COLUMN skills.original_prompt IS 'El prompt original que escribió el usuario';

COMMENT ON TABLE votes IS 'Votos anónimos por IP (sin login requerido)';
COMMENT ON COLUMN votes.ip_hash IS 'Hash SHA256 de IP (no guardamos IP real por GDPR)';
